### PR TITLE
Add correct libraries to appveyor debug build, #77

### PR DESCRIPTION
**Pull request by crayxt**

### CODE REVIEW

**Comment by crayxt** [comment]
Somehow linked with release dlls, need to look into

**Comment by crayxt** [comment]
Debug build needs debug version of log4cpp library - will add.

**Comment by markummitchell** [comment]
The travis and appveyor files look like a lot of work. Congratulations on succeeding. If you want to merge, please feel free.

**Comment by crayxt** [comment]
@markummitchell Since I cannot squash this PR to single commit (I edit with web only) I will create a new, clean PR.
Debug builds from appveyor now work, documentation is also included.

**Comment by crayxt** [comment]
Closed in prior of https://github.com/markummitchell/engauge-digitizer/pull/93

**Pull request closed without merging**
