### PR TITLE
Update ParseDig.py

### PR DESCRIPTION
**Pull request by kylesower**
Update to allow for export of plots with four axis points defined

### CODE REVIEW

**Comment by kylesower** [comment]
After testing my script on a large number of files, I realized that it doesn't work for files which have an infinite slope (i.e. the x pixels on the y-axis points match exactly, giving a division error). I'll work on fixing this tomorrow.
Also looking to add support for log plots later; for now I just separated them from my other files.

**Comment by markummitchell** [comment]
Do you mind if I add your name to the Project page?

**Comment by kylesower** [comment]
I don't mind.

**Comment by markummitchell** [comment]
I added your name. with a link to your github account. If you have another url, that can be used instead.

**Comment by kylesower** [comment]
Thank you! That works fine.

**Pull request merged**
