### PR TITLE
Switch appveyor builds to Visual Studio 2015.

### PR DESCRIPTION
**Pull request by crayxt**
Per https://github.com/markummitchell/engauge-digitizer/issues/210

### CODE REVIEW

**Comment by crayxt** [comment]
Ok, it is compiled but cannot be run - I think supporting libraries log4cpp and poppler-qt5 should be compiled in VC2015 as well.

**Comment by markummitchell** [comment]
I'm back after a few days offline. I merged the branch. Anything else I should do?

**Comment by crayxt** [comment]
Yes I'd like to know how to switch appveyor builds to your version of log4cpp

**Comment by markummitchell** [comment]
You should now have access to my log4cpp_null drop in replacement for
log4cpp. You can make changes if you want. I hope that was what you were
looking for.

**Pull request merged**
