### PR TITLE
Enable poppler library and fix debug release.

### PR DESCRIPTION
**Pull request by crayxt**

### CODE REVIEW

**Comment by crayxt** [comment]
I am afraid this is bit too early, zlib library is somehow broken

**Comment by crayxt** [comment]
@markummitchell How do we select a page on PDF import?

**Comment by crayxt** [comment]
although I am not quite happy with newly bundled libraries - they are obsolete.

**Comment by crayxt** [comment]
Continued in https://github.com/markummitchell/engauge-digitizer/pull/142

**Comment by crayxt** [comment]
still curious - @markummitchell How do we select a page on PDF import?

**Comment by markummitchell** [comment]
I think that would take a new dialog that would be opened each time a PDF file is read, with the page, and optionally the picture boundaries, selected by the user. I'm not available to spend time on new features for a while but would welcome any donations.

**Comment by markummitchell** [comment]
I found some time to work on this, as issue #143. The user can pick a page and a region in that page.

**Comment by crayxt** [comment]
@markummitchell wow, thanks!

**Comment by crayxt** [comment]
The appveyor-poppler-and-debug-fix branch could be deleted now

**Pull request merged**
