### PR TITLE
Formatting fixes with clang-format.

### PR DESCRIPTION
**Pull request by crayxt**
Test compilation of clang-formatter sources.

### CODE REVIEW

**Comment by crayxt** [comment]
Clang on OSX errored out ;)

**Comment by markummitchell** [comment]
I am inclined to not use the clang formatting. The code already has a style that has been applied consistently, with my external and the QtCreator editors supporting that format. If you open up the QtCreator tool and find the language settings, you'll see that there are various 'standard' formats, and Engauge is using one of them. I've tried to make the code very readable.

**Comment by crayxt** [comment]
Ok

**Comment by markummitchell** [comment]
I put headers into the cpp and h files. By the way, the code is formatted for doxygen document generation. If doxygen is installed, you can run doxygen in the src directory to auto-generate code documentation - this is for developers and not users. Also, installing cccc and running docccc in the src directory generates code metrics. Doxygen and cccc are both 'best practices'.

**Pull request closed without merging**
